name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_music: yes
          plugin_music_provider: "lastfm"
          plugin_music_token: ${{ secrets.LASTFM_KEY }}
          plugin_music_user: "t_ube"
          plugin_music_mode: "top"
          plugin_music_playlist: "https://open.spotify.com/embed/playlist/37i9dQZF1EphpDoTGzKuzb?utm_source=generator"
          plugin_music_limit: 5
          
